name: hello_web3
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  username_generator: ^1.3.0
  web3dart: ^2.3.5
  web_socket_channel: ^2.2.0
  web_three_client:
    path: packages/web_three_client
  web_three_repository:
    path: packages/web_three_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - web3/artifacts/HelloWeb3.json
    - .env

